services:
  app:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      target: dev
    ports:
      - "3151:3151"
      - "11113:11113"
    volumes:
      - ./app:/app
      - ./tools:/tools
      - ./.castor:/.castor
      - ~/.ssh:/home/www-data/.ssh:ro
      - user_data:/home/www-data
    labels:
      - "traefik.enable=true"
      - "traefik.network=traefik"
      - "traefik.http.routers.php-mantine-starter-kit.rule=Host(`mantine-starter-kit.web.localhost`)"
      - "traefik.http.routers.php-mantine-starter-kit.tls=true"
      - "traefik.http.services.php-mantine-starter-kit.loadbalancer.server.port=80"
    networks:
      - traefik
    profiles:
      - app
    extra_hosts:
      - host.docker.internal:host-gateway

  mariadb:
    ports:
      - "3351:3306"
    profiles:
      - app

  mkdocs:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mkdocs-mantine-starter-kit.rule=Host(`mantine-starter-kit.docs.localhost`)"
      - "traefik.http.routers.mkdocs-mantine-starter-kit.tls=true"
      - "traefik.http.services.mkdocs-mantine-starter-kit.loadbalancer.server.port=8000"
    networks:
      - traefik
    profiles:
      - app

networks:
  traefik:
    external: true

volumes:
  user_data: